config/routes.rb
Rails.application.routes.draw do
  get 'bedsitters/index'
  


resources :appartments
resources :bedsitters
root 'bedsitters#index'

end

app/models/agent.rb
class Agent < ActiveRecord::Base
end

app/models/appartment.rb
class Appartment < ActiveRecord::Base
end

app/models/bedsitter.rb
class Bedsitter < ActiveRecord::Base
end

app/controllers/appartments_controller.rb
class AppartmentsController < ApplicationController
	def index
		
	end

	def new
		@
	end

	def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bedsitters_controller.rb
class BedsittersController < ApplicationController
  def index
  end
end

app/helpers/appartment_helper.rb
module AppartmentHelper
end

app/helpers/appartments_helper.rb
module AppartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bedsitters_helper.rb
module BedsittersHelper
end

app/views/appartments/index.html.erb
<h1>Apartment Information</h1>



<%= simple_form_for :appartment, url: appartments_path do |form| %>
  <%= form.input :title, label: "Apartment Name" %>
  <br>
  <%= form.input :text, label: "Apartment Description" %>
  <br>
  <%= form.input :image_url, label: "Apartment Image" %>
  <br>
  <%= form.button :submit %>
<% end %>

app/views/appartments/new.html.erb
<h1>Apartment Information</h1>



<%= simple_form_for :appartment, url: appartments_path do |form| %>
  <%= form.input :title, label: "Apartment Name" %>
  <br>
  <%= form.input :text, label: "Apartment Description" %>
  <br>
  <%= form.input :image_url, label: "Apartment Image" %>
  <br>
  <%= form.button :submit %>
<% end %>

app/views/bedsitters/index.html.erb
<h1>Bedsitters#index</h1>
<p>Find me in app/views/bedsitters/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Properties</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>